# name: Publish Lackey Plugin
# on:
#   push:
#     branches:
#       - 'master'

# defaults:
#   run:
#     shell: bash
#     working-directory: _lackey

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkoutï¸ ğŸ›
#         uses: actions/checkout@v2
#         with:
#           persist-credentials: true

#       - name: Deploy Plugin ğŸš€
#         uses: JamesIves/github-pages-deploy-action@releases/v3
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           BRANCH: gh-pages
#           FOLDER: _site
#           TARGET_FOLDER: lackey
#           SINGLE_COMMIT: true
#           CLEAN: true
